### ISSUE TITLE
create asciidoc template for question types

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#61]
to make migration from docx a little easier...

**Comment by gernotstarke** [comment]
done

**Comment by rhoadesre** [comment]
I still see the docx files. Did you already create the adoc files?

**Comment by gernotstarke** [comment]
We started in raw/mock/asciidoc

Dr. Gernot Starke
+49-177-7282570
***@***.***
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.

**Comment by programming-wolf** [comment]
Yes, they are in a separate branch.
